# Generated by Django 5.2 on 2025-04-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='designation',
            field=models.CharField(choices=[('In Charge', 'incharge'), ('Staff', 'staff')], default='staff', max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'super admin'), ('Admin', 'admin'), ('Staff', 'staff')], default='user', max_length=20),
        ),
    ]
