# Generated by Django 5.2 on 2025-04-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_designation_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='designation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(choices=[('In Charge', 'incharge'), ('Staff', 'staff')], default='staff', max_length=25),
        ),
    ]
