# Generated by Django 5.2 on 2025-04-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_department_designation_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'super admin'), ('Admin', 'admin'), ('Staff', 'staff')], default='USER', max_length=20),
        ),
    ]
