# Generated by Django 5.2 on 2025-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'super admin'), ('Admin', 'admin'), ('User', 'user')], default='USER', max_length=20),
        ),
    ]
