# Generated by Django 5.2 on 2025-04-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_status_predefine_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='define_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.predefine_complaint'),
        ),
    ]
