# Generated by Django 5.2 on 2025-04-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_define_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='define_complaint',
        ),
        migrations.DeleteModel(
            name='Predefine_Complaint',
        ),
    ]
