# Generated by Django 5.2 on 2025-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complainthistory_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainthistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
