# Generated by Django 5.2 on 2025-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complainthistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainthistory',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
