# Generated by Django 5.2 on 2025-04-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complainthistory_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainthistory',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='complainthistory',
            name='remark',
        ),
    ]
