# Generated by Django 5.2 on 2025-04-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
