# Generated by Django 5.2 on 2025-04-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_assignmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenthistory',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='assignmenthistory',
            name='resolved_by',
        ),
    ]
