# Generated by Django 5.2 on 2025-04-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_reassignedcomplaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
    ]
